### ISSUE TITLE
Feature Request: Add a userscript file for extensions like tampermonkey

### ISSUE THREAD

**Issue by kun-codes** [puiooo/startpage_enhancer#3]

**Comment by mriooo** [comment]
Please elaborate this a bit more, how does this work? Got any links for me? 😄

**Comment by Elaborendum** [comment]
You add a .user.js that achieves the same functionality as the addon to the repo, so that those with any userscript addon* may simply click it to add it to the addon and receive updates from it. Some prefer to install small extensions as userscripts instead. More info [here](https://wiki.greasespot.net/Metadata_Block) and the rest of that wiki.

*Of which there are three main -monkey addons, GreaseMonkey, ViolentMonkey and TamperMonkey. Grease is the oldest one and may miss some features that the other two have, but it's still used by many.

Sometimes you may need to change some things to adapt it to an userscript.  I've been manually using the contents of `enhance.js` as an userscript for a few months and only the favicons seem to be broken, but I'm not exactly sure if everything else is in working order or if it's just me. 

I use the following as the match list, but I'm not sure if right.
```
// @match       https://startpage.com/search?q=*
// @match       https://startpage.com/sp/search*
// @match       https://www.startpage.com/sp/search*
// @match       https://startpage.com/do/dsearch*
// @match       https://www.startpage.com/do/dsearch*
```

**Comment by mriooo** [comment]
cool! Will look into it when I got more time to spare. Sounds nice.

**Comment by ueen** [comment]
i added this to the readme https://github.com/puiooo/startpage_enhancer/pull/10

anyone using tampermonkey or something similar should be able to add it with this in seconds

adding it to a a userscript repo would be additional work for each update and it would be extermely hard to find as there are several userscripts repos and this is a rather special interest (117 downlods in firefox store) so dont really see this being worth the effort :)

**Comment by mriooo** [comment]
i am on this with @ueen

**Comment by ueen** [comment]
Actually the head is just comments so if it is added to enhance.js it could be used as a userscript without copying and enhance.js could also be changed to user.js if it's also changed in the manifest there's no real difference :)
